name: leader24-website
region: fra
services:
- build_command: npm install && npm run build
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: DATABASE_URL
    type: SECRET
    scope: RUN_TIME
  - key: SESSION_SECRET
    type: SECRET
    scope: RUN_TIME
  - key: OPENAI_API_KEY
    type: SECRET
    scope: RUN_TIME
  - key: SENDGRID_API_KEY
    type: SECRET
    scope: RUN_TIME
  - key: PORT
    value: "8080"
    scope: RUN_TIME
  github:
    branch: main
    deploy_on_push: true
    repo: your-github-repo/your-repo-name
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: web
  run_command: npm start
  source_dir: /
  health_check:
    http_path: /
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3